### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by killo3967** [OwO-Network/DeepLX#40]
I have implemented in the translation comicrack plugin the call to your 'DeepL X' and it works very well but after a while of translating it has blocked me. In fact, it doesn't even let me translate from the web. I am attaching the log that the caliber plugin gives me.

======================== BEGIN LOG =============================
.
.  A lot of translations before......
.
------------------------------
Original: It took the Torch soldiers no more than four or five seconds to get the slaver rolled over and haul Takahashi off him, but by then she’d pretty well transformed a third of his frontal lobes into hash. The autopsy ’bot later reported that she’d carved up part of the limbic system as well.
Traducción: Los soldados de la Antorcha no tardaron más de cuatro o cinco segundos en hacer rodar al esclavo y quitarse a Takahashi de encima, pero para entonces ya había transformado en hachís un tercio de sus lóbulos frontales. El robot de la autopsia informó más tarde de que también había cortado parte del sistema límbico.
------------------------------
Original: Modern medicine is not actually miraculous, although the term is often used. For all practical purposes, the man was gone before any aid could be given him.
No se pudieron recuperar los datos de la API del motor de traducción.
Se volverá a intentar en 5 segundos.

Reintentando... (el tiempo de espera es de 300 segundos).
No se pudieron recuperar los datos de la API del motor de traducción.
Se volverá a intentar en 10 segundos.

Reintentando... (el tiempo de espera es de 300 segundos).

No se pudieron recuperar los datos de la API del motor de traducción.
Se volverá a intentar en 30 segundos.

Reintentando... (el tiempo de espera es de 300 segundos).
Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 81, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 59, in _translate
  File "calibre_plugins.ebook_translator.engines.custom", line 120, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 88, in get_result
Exception: No se pudo analizar la respuesta devuelta. Datos sin procesar: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 81, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 59, in _translate
  File "calibre_plugins.ebook_translator.engines.custom", line 120, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 88, in get_result
Exception: No se pudo analizar la respuesta devuelta. Datos sin procesar: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 81, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 59, in _translate
  File "calibre_plugins.ebook_translator.engines.custom", line 120, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 88, in get_result
Exception: No se pudo analizar la respuesta devuelta. Datos sin procesar: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.engines.base", line 81, in get_result
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.ebook_translator.translation", line 59, in _translate
  File "calibre_plugins.ebook_translator.engines.custom", line 120, in translate
  File "calibre_plugins.ebook_translator.engines.base", line 88, in get_result
Exception: No se pudo analizar la respuesta devuelta. Datos sin procesar: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\utils\ipc\worker.py", line 150, in arbitrary_n
  File "calibre_plugins.ebook_translator.convertion", line 124, in convert_book
  File "calibre\ebooks\conversion\plumber.py", line 1281, in run
  File "calibre_plugins.ebook_translator.convertion", line 120, in convert
  File "calibre_plugins.ebook_translator.translation", line 109, in handle
  File "calibre_plugins.ebook_translator.translation", line 87, in _handle
  File "calibre_plugins.ebook_translator.translation", line 71, in _translate
  File "calibre_plugins.ebook_translator.translation", line 71, in _translate
  File "calibre_plugins.ebook_translator.translation", line 71, in _translate
  File "calibre_plugins.ebook_translator.translation", line 63, in _translate
Exception: No se pudieron recuperar los datos de la API del motor de traducción. No se pudo analizar la respuesta devuelta. Datos sin procesar: HTTP Error 429: Too Many Requests

======================== END LOG =============================

**Comment by missuo** [comment]
#39

**Comment by killo3967** [comment]
Hi. 
I comment this with the translator plugin for Calibre. The I create an random sleep delay between 1 and 15 seconds and the final result is identical. DeepL detect "HTTP Error 429: Too Many Requests". 
Did you test your software with big text like a book ?

**Comment by missuo** [comment]
> Hi. 
> 
> I comment this with the translator plugin for Calibre. The I create an random sleep delay between 1 and 15 seconds and the final result is identical. DeepL detect "HTTP Error 429: Too Many Requests". 
> 
> Did you test your software with big text like a book ?

I don't recommend it for an entire book. This will definitely trigger DeepL's official risk control. This is out of my control, I hope you can understand.

**Comment by killo3967** [comment]
Yes, I understand that, but it is a pity that it cannot be used for the translation of books, because DeepL is better than Google for this.
